강성훈(자기소개)
BCSDLab-Edu/git-introduction pull request #10
Opened 2024-03-15 07:17 UTC by kang-s-h

2024-03-20 03:15 UTC, Choi-JJunho requested changes
고생하셨습니다~
Good First PR!
학번, 이름, 지원 트랙 정보에 대해 내용이 비어있네요 ㅠㅠ
확인 부탁드립니다

2024-03-20 03:15 UTC, Choi-JJunho commented on introduction.txt
>  지원 트랙:
학번, 이름, 지원트랙이 비어있네요 ㅠㅠ

2024-03-20 03:15 UTC, Choi-JJunho commented on introduction.txt
> +취미: 운동
어떤 운동 좋아하시나요?

2024-03-25 10:19 UTC, kang-s-h commented on introduction.txt
>  지원 트랙:
제가 변경을 하려다 파일이 날라가서 web과제 제출에 다시 올렸습니다!

2024-03-25 10:19 UTC, kang-s-h commented on introduction.txt
> +취미: 운동
축구도 좋아하고 헬스도 좋아합니다!

2024-09-22 23:41 UTC, closed without merging